### ISSUE TITLE
Collaborative Filtering error

### ISSUE THREAD

**Issue by hermandr** [radiant-rstats/radiant.multivariate#1]
I followed the instructions for example
1. Data - select Ratings dataset, Data/View set filter training==1
2. Multivariate/Collaborative filtering
    - user id: Users
    - product: Movies
    - choose products to recommend: M1-M10
    - Ratings variable: Ratings
3. Click on estimate model

![image](https://user-images.githubusercontent.com/10177608/100301908-caaaf480-2fcb-11eb-95ef-c57affb75db9.png)

"Cannot predict for all products. Ratings must overlap on at least two products."

**Comment by hermandr** [comment]
Sorry I missed a small detail:
Examples says to choose set of products to predict on M6-M10.

However, I am not able to plot as it says to provide dataset with new data.
I go to data View and set the training filter == 0.

I go back to collaborative filtering and the green button asks to re-estimate the model.
Plot does not show anything.

How do I use the user interface for model estimation using train data set and then predict on new dataset?

Herman

**Comment by vnijs** [comment]
@hermandr I replied to your other post for the `radiant.model` package. I assume that will address your question. For collaborative filtering, you need the actual responses for the plots to be generated. You could try the code below in or outside of the radiant interface. Your interests seems to be mostly on training and test so please take a look at the video linked below.

https://youtu.be/9fugq5dXNhk

That said, you might also be interested in the "Radiant Tutorial Series"

https://radiant-rstats.github.io/docs/radiant-tutorial-series.html

```
library(radiant)
ratings <- data(ratings, package = "radiant.model", envir = environment()) %>% get()
register("ratings")

ratings <- ratings %>%
  filter(Users != "U11")

result <- crs(
  ratings, 
  id = "Users", 
  prod = "Movies", 
  pred = c("M5", "M6", "M7", "M8", "M9", "M10"), 
  rate = "Ratings", 
  data_filter = "Users %in% paste0('U', 5:10)"
)
summary(result)
plot(result)
```
