### ISSUE TITLE
Correlations plot - choice of axes

### ISSUE THREAD

**Issue by jacobbien** [radiant-rstats/radiant.multivariate#3]
Hi there!

The labeling of correlation plot axes is the opposite of what I would expect.  Consider, for example, a linear model of price ~ carat on the diamonds data:

![Screen Shot 2022-10-19 at 11 20 08 AM](https://user-images.githubusercontent.com/2008608/196773195-d1bd7311-a882-4fad-8f8e-a75ff2cb9298.png)

Based on this labeling, I would think that the scatter plot has price on the x-axis and carat on the y-axis.  However, if we switch from the correlations plot to the scatter plot, we get the following:

![Screen Shot 2022-10-19 at 11 20 26 AM](https://user-images.githubusercontent.com/2008608/196773914-c35e801c-f3b6-458b-836d-8095098bfdf0.png)

I guess it's a matter of taste/convention, but I did confirm that my assumptions about the meaning of the axis labeling is based on what the `pairs` function in R does:

![Screen Shot 2022-10-19 at 11 20 49 AM](https://user-images.githubusercontent.com/2008608/196774046-739d45d4-86dd-411e-ae51-88e630408c1d.png)

**Comment by vnijs** [comment]
Didn't realize that. Thanks for reaching out. I agree that "it's a matter of taste/convention". Since radiant has had this setup for a long time I'll keep the order as is.
